# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 10:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=200)),
                ('designation', models.CharField(default='', max_length=100)),
                ('section', models.CharField(default='', max_length=100)),
                ('authority', models.CharField(default='', max_length=100)),
                ('otherauthority', models.CharField(default='', max_length=100)),
                ('mail', models.CharField(default='', max_length=200)),
                ('jobtype', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
