# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170828_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='processing_status',
            field=models.CharField(choices=[('Head CSE', 'Head CSE'), ('Head ECE', 'Head ECE'), ('Head ME', 'Head ME'), ('Head NS', 'Head NS'), ('Head Design', 'Head Design'), ('Director', 'Director')], default='Director', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='station_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='station_leave',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='station_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='remainingleaves',
            name='earned',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='remainingleaves',
            name='vacation',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
