# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_leave_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainingleaves',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
