# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remainingleaves_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='station_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='station_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remainingleaves',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remaining_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
