# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170831_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='remainingleaves',
            name='vacation',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
